### ISSUE TITLE
How to disable firepad?

### ISSUE THREAD

**Issue by etcy** [rdbeach/wb#5]
Hi, 

I think your improvements over the original is really cool. 

I'm trying to use this at work for a medium sized team but the company rejected my proposal because of the need to register with firebase and external data use. I need this to be totally self hosted. 

Is there a way to disable firepad?

**Comment by wraith11** [comment]
I'm not an expert but I havn't configured firepad so it shouldn't connect anywhere and all works fine.

If you want to disable it entirely try to remove the whole "wb-editor-container" div ( lines 87 - 116 ) and everything between
`<!-- BEGIN EDITOR TOOL -->`
and
`<!-- END EDITOR TOOL-->`
in "client-data/board.html".

And remove the directory "client-data/tools/editor" .

I've not tested this but it may worth a try.

Edit: I've forgotten the `<!-- Modal -->` part. So remove lines 87 - 137 from "client-data/board.html".

**Comment by etcy** [comment]
Great! I followed your instructions and the button for editor is now gone!

I have another issue. At first I thought it was due to fire base stuff not properly set up.
I can access the site, I can draw and so but in the middle of the screen, "Loading...." is always showing.
I get this on both fire fox and chrome.

After disabling fire pad, "Loading..." still does not go away.

On chrome, the console shows this:

GET http://10.0.0.33:8080/socket.io/?EIO=3&transport=polling&t=NGqJGMm net::ERR_CONNECTION_REFUSED

-------------
I am running this on Centos 8.
Using the following command:
PORT=7001 npm start

node -v gives: v12.18.3
-------------

I think the following issue is the same?
[cannot install](https://github.com/rdbeach/wb/issues/1)

**Comment by wraith11** [comment]
The problem is that the port 8080 is kinda hardcoded - it's mentioned in README.md
> If you want to run on a different port, you will need to change the PORT=8080 in the line above, and modify this line in /client-data/js/board.js:
> 
> this.socket = io.connect(':8080', {

**Comment by etcy** [comment]
Thank you for the quick response! Your answer is spot on.
Its my bad for not reading the README.md
